### ISSUE TITLE
App does not work offline properly

### ISSUE THREAD

**Issue by VibhaThakur** [expo/native-component-list#4]
I upgrade my app in expo-25. In standalone android app, when I launch app offline, Its working fine but some images are not shown. Other problem is when I kill the app and again open app, it shows error: "Unknown Error: java.net.UnknownHostException". Unable to resolve host "exp.host": No address associated with hostname.
Also I have check this example. Second time it does not launch without Internet
Could you please help?

**Comment by dale-french** [comment]
I am experiencing the same issue - if I open the app with connectivity, then close the app, switch off connectivity and then open it again I get the error below:

`Uncaught Error: java.net.UnknownHostException: Unable to resolve host "exp.host": No address associated with hostname`

Then, if I close the app again, switch on connectivity, open the app (runs fine while online now) and then close it, switch off connectivity and open again it seems to work online.

**Comment by anp** [comment]
Hi! It doesn't sound like these issues are related to native-component-list, do you think you could open an issue on https://github.com/expo/expo? Thanks!
