### ISSUE TITLE
Editing Images is not canceled when abort Picker

### ISSUE THREAD

**Issue by Effizjens** [expo/native-component-list#5]
Hi,

when you click on the "Pick Photo And Edit" Button, abort the ImagePicker and click on "Pick Photo Or Video" the editing mode is still active.
Changing this [Line](https://github.com/expo/native-component-list/blob/master/screens/ImagePickerScreen.js#L26) to
"let result = await ImagePicker.launchImageLibraryAsync({allowsEditing: false});"
should fix it.

EDIT: Same thing in line 15 with the camera. Adding "allowsEditing:false" should fix it.

**Comment by ide** [comment]
Native Component List has now moved here: https://github.com/expo/expo/tree/master/apps/native-component-list. We'll open a new issue on the Expo repo that points to this one.
