### ISSUE TITLE
Uncaught Error: 26.0.0 is not a valid sdk version.

### ISSUE THREAD

**Issue by eabaid** [expo/native-component-list#6]
Uncaught Error: 26.0.0 is not a valid sdk version.
Options are 25.0.0, 24.0.0, 23.0.0, 22.0.0, 21.0.0, 20.0.0, 19.0.0, UNVERSIONED.

Steps to Reproduce:

`git clone https://github.com/expo/native-component-list.git`
`cd native-component-list`
`npm install`
`exp start`

Uninstalled Expo app and reinstalled on Android device via Google Play.
In Expo app, scanned QR code generated by `exp start`.

**Comment by anp** [comment]
Hi! This app has been updating for the pending SDK release, but not all of our tools and versions information has yet. I think if you checkout https://github.com/expo/native-component-list/commit/29e27278b7d715aaac8d85566db6d9462ba999f1 you should be able to build it yourself. One thing to note is that we regularly publish this to https://expo.io/@community/native-component-list if you'd just like to load it.

**Comment by eabaid** [comment]
I see. Thanks @anp !
