### ISSUE TITLE
native-component-list Expo.Calendar example not working 

### ISSUE THREAD

**Issue by hskb10** [expo/native-component-list#7]
Hi guys!

Just want to give a heads up, the Expo.Calendar in native-component-list is not working. In iOS it shows the "Find my Calendar" Button, but does not forward to any new views and does not throw any error. In Android it outright throws Permission error as you navigate to the expo calendar api view. 
Did some digging and so far here's what I've found: 
- On the expo docs, Permissions.CALENDAR was not required. Experimented commenting it out. Android stopped throwing the Permssion error, but expo app would crash when "Find my Calendar" button was tapped. iOS, it wouldn't open and there were no errors/warning communicated. (will dig deeper)

To see if the api (based on react-native-calendar) still works I tested both Android and iOS by running @brentvatne [example-react-native-calendar](https://github.com/expo/examples/tree/master/with-react-native-calendars) and I'm glad to say that it works. So react-native-calendar is an option for those who need a calendar api that is compatible with expo.

Thank you!

**Comment by hskb10** [comment]
A quick fix was found here: [expo-forums-calendar](https://forums.expo.io/t/using-new-calendar-api/7346/2)

**Comment by esamelson** [comment]
I think this might be resolved once SDK 26 is out and `Permissions.CALENDAR` is defined (whoops). (Note that this repo is updated for SDK 26 which is not out yet on the clients, so that might be causing some confusion.) For SDK 25, requesting `Permissions.askAsync('calendar')` should do the trick, but let me know if that still doesn't work @hskb10 .

**Comment by hskb10** [comment]
Thank you @esamelson. It is working. Have a great week!

**Comment by ide** [comment]
Closing this issue since it has been resolved.
