### ISSUE TITLE
Unable to run the project

### ISSUE THREAD

**Issue by gagaJay** [expo/native-component-list#9]
Hi, Im really new to react native so I downloaded your project as studying code for me. The project, however, somehow can not be run.

when I tried to run
**react-native run-ios**
it says "iOS project folder not found. Are you sure this is a React Native project?"

so then I tried
**npm start**
The output prints "missing script: start"

Then I copied the default script to your project as below:
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "jest"
  },

But still doesn't work. 

Please someone helps me with this. Thanks.

**Comment by rankun203** [comment]
@gagaJay Hey Gaga, you can follow [this page](https://docs.expo.io/versions/v28.0.0/introduction/installation) to install XDE and use that as a development server.

**Comment by ide** [comment]
Native Component List has now moved here: https://github.com/expo/expo/tree/master/apps/native-component-list. I also recommend getting the Expo developer tools (most recently, [Expo CLI 2.0](https://blog.expo.io/expo-cli-2-0-released-a7a9c250e99c)) and running the project that way.
